language: ruby
rvm:
  - "2.1.4"

before_script:
  - psql -c 'create database dev_social_test;' -U postgres
  - psql -c 'create database dev_social_production;' -U postgres
  - psql -c 'create database dev_social_development;' -U postgres


# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
